apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-demo-jvm-deployment
  labels:
    app: quarkus-demo-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-demo-jvm
  template:
    metadata:
      labels:
        app: quarkus-demo-jvm
    spec:
      containers:
      - name: quarkus-demo-jvm
        image: quay.io/nimmo_rh/quarkus-demo-jvm:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP