kind: Service
apiVersion: v1
metadata:
  name: quarkus-demo-jvm-service
  labels:
    app: quarkus-demo-jvm
spec:
  selector:
    app: quarkus-demo-jvm
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP